### ISSUE TITLE
Upgrading to Bower 1.3 causes errors

### ISSUE THREAD

**Issue by abovethewater** [abovethewater/grunt-bower-seamless-install#2]
As noted in PR #1 When updating bower version to 1.3.12 tests fail to pass

> grunt test

```
Running "clean:tests" (clean) task

Running "mkdir:tmp" (mkdir) task

Running "write:bower.json:{"name"\: "fake", "dependencies"\: {"underscore"\:""}}" (write) task

Running "write:.bowerrc:{"directory"\: "tmp/bower_components"}" (write) task
|
Running "bower-install" task
-
Running "bower-install:jquery#1.11.0" (bower-install) task
/
Running "bower-install:q" (bower-install) task
\
Running "bower-install:lodash:async" (bower-install) task
\
Running "nodeunit:tests" (nodeunit) task
Testing bower-install_test.jsF
>> bower_install - bower-install
>> Message: Component should have been installed.
>> Error: Component should have been installed.
>> at Object.exports.bower_install.bower-install (test/bower-install_test.js:30:10)

>> bower_install - bower-install
>> Message: Versioned component should have been installed.
>> Error: Versioned component should have been installed.
>> at Object.exports.bower_install.bower-install (test/bower-install_test.js:32:10)

>> bower_install - bower-install
>> Error: Expected 5 assertions, 2 ran

>> bower_install - bower-install
>> Error: Unable to read "./tmp/bower_components/jquery/bower.json" file (Error code: ENOENT).
>> at Object.util.error (node_modules/grunt/node_modules/grunt-legacy-util/index.js:54:39)
>> at Object.file.read (node_modules/grunt/lib/grunt/file.js:247:22)
>> at Object.file.readJSON (node_modules/grunt/lib/grunt/file.js:253:18)
>> at Object.exports.bower_install.bower-install (test/bower-install_test.js:34:34)
```

**Comment by abovethewater** [comment]
Looks to be related to first run of tests.

After first run they work fine, but running

```
git clean -X -f
```

To remove ignored files causes the tests to fail
